import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,History as HistoryIcon,ChartNoAxesCombined,Bot,User,Utensils,ArrowLeft,ChevronRight,Camera,Search,Mic,Image,Send,Bell,Target,Shield,HelpCircle,Info,Sparkles} from 'lucide-react';
import './styles.css';

const nav=[['home','Home',Home],['history','History',HistoryIcon],['progress','Progress',ChartNoAxesCombined],['ai_coach','AI Coach',Bot],['profile','Profile',User]];
const meals=[['Breakfast','Quick yoghurt bowl',410,true,'🥣'],['Lunch','Chicken grain bowl',560,true,'🥗'],['Dinner','Plan your protein-rich dinner',0,false,'🍽️'],['Snack','Nothing logged yet',0,false,'🍎']];
const trends=[['Mon',.25],['Tue',.32],['Wed',.55],['Thu',.62],['Fri',.60],['Sat',.66],['Today',.95]];
function path(){return location.hash.replace('#/','')||'splash'} function go(p){location.hash='/'+p}
function Icon({C,...p}){return <C size={20} strokeWidth={1.9} {...p}/>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Button({children,onClick,outline=false,small=false}){return <button className={'btn '+(outline?'outline ':'')+(small?'small':'')} onClick={onClick}>{children}</button>}
function Logo({large=false}){return <div className={'logo '+(large?'large':'')}><Utensils size={large?52:25}/></div>}
function Top({title,back=true,right}){return <header className="top">{back?<button className="iconBtn" onClick={()=>history.length>1?history.back():go('home')}><ArrowLeft/></button>:<div/>}<h2>{title}</h2>{right||<div className="topSpace"/>}</header>}
function Bottom({active}){return <nav className="bottom">{nav.map(([r,l,C])=><button key={r} className={active===r?'active':''} onClick={()=>go(r)}><Icon C={C}/><span>{l}</span></button>)}</nav>}
function Shell({children,active,wide=false}){return <div className={'app '+(wide?'wide':'')}><main className="content">{children}</main>{active&&<Bottom active={active}/>}</div>}
function Splash(){setTimeout(()=>go('login'),900);return <div className="splash"><Logo large/><h1>AI Nutrition Coach</h1><p>Smart, personalized nutrition tracking</p><div className="spinner"/></div>}
function Login(){const [email,setEmail]=useState('');const [pw,setPw]=useState('');return <div className="auth"><Logo large/><h1>Welcome Back</h1><p>Log in to track your nutrition goals</p><div className="form"><label>Email Address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com"/></label><label>Password<input value={pw} onChange={e=>setPw(e.target.value)} type="password" placeholder="••••••••"/></label><div className="row between"><label className="check"><input type="checkbox"/> Remember me</label><button className="link" onClick={()=>go('forgot_password')}>Forgot Password?</button></div><Button onClick={()=>go('home')}>Log In</Button><div className="or"><span/>or<span/></div><div className="social"><button><b>G</b> Continue with Google</button><button><b>f</b> Continue with Facebook</button></div><p className="center">Don't have an account? <button className="link" onClick={()=>go('register')}>Sign Up</button></p></div></div>}
function Register(){return <div className="auth"><button className="backTop" onClick={()=>go('login')}><ArrowLeft/> Back</button><Logo large/><h1>Create Account</h1><p>Start your personalized nutrition journey</p><div className="form"><label>Full Name<input placeholder="Your name"/></label><label>Email Address<input placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="Create a password"/></label><label>Confirm Password<input type="password" placeholder="Repeat password"/></label><Button onClick={()=>go('home')}>Create Account</Button><p className="center">Already have an account? <button className="link" onClick={()=>go('login')}>Log In</button></p></div></div>}
function Forgot(){return <div className="auth"><button className="backTop" onClick={()=>go('login')}><ArrowLeft/> Back</button><Logo large/><h1>Forgot Password?</h1><p>Enter your email and we'll send you a reset link.</p><div className="form"><label>Email Address<input type="email" placeholder="you@example.com"/></label><Button onClick={()=>go('login')}>Send Reset Link</Button></div></div>}
function Header(){return <div className="wlHeader"><button className="iconBtn"><MoreVertical/></button><div className="greet">Good morning, Gogo Ji 👋</div><div className="headRight"><button className="round"><Bell size={18}/><i>3</i></button><button className="avatar" onClick={()=>go('profile')}><User size={19}/></button></div></div>}
function Home(){return <Shell active="home"><div className="page"><Header/><Card className="hero"><div><h3>Weight journey</h3><p>A steady path, one healthy choice at a time.</p></div><Button small onClick={()=>go('goal')}>↔ Switch Goal</Button><div className="weights"><div><small>Current weight</small><strong>181.4 <em>lb</em></strong></div><div className="goal"><small>Goal weight</small><strong>165 <em>lb</em></strong></div></div><div className="heroBottom"><span>13.7 lb lost</span><span>45% of your journey</span><span>16.4 lb to go</span></div><div className="bar"><i style={{width:'45%'}}/></div></Card><section><div className="sectionHead"><div><small>TODAY'S FOCUS</small><h3>Stay on track</h3></div><button className="link" onClick={()=>go('progress')}>See plan <ChevronRight size={15}/></button></div><div className="focusGrid"><Metric icon="🔥" label="Calories" value="1420 / 1800" pct={79}/><Metric icon="🥚" label="Protein" value="92 / 120 g" pct={77}/><Metric icon="💧" label="Water" value="5 / 8" pct={63}/><Metric icon="👟" label="Steps" value="6420 / 8000" pct={80}/></div></section><div className="actionRow"><Button onClick={()=>go('food_analysis')}>＋ Log a Meal</Button><Button outline onClick={()=>go('food_analysis')}>⌁ Scan Food</Button></div><Card><div className="sectionHead"><div><small>TODAY'S NUTRITION</small><h3>1420 kcal <span className="muted">of 1800 kcal</span></h3></div></div><div className="macros"><Macro label="Protein" value="92g" pct={77}/><Macro label="Carbs" value="146g" pct={73}/><Macro label="Fat" value="48g" pct={74} coral/></div></Card><Card><div className="trendHead"><div><h3>Weight Trend</h3><p>Last 7 days</p></div><div className="trendValue">181.4 lb<br/><span>↘ 1.8 lb this month</span></div></div><div className="bars">{trends.map(([d,v])=><div key={d}><i className={d==='Today'?'today':''} style={{height:(v*65)+'px'}}/><small>{d}</small></div>)}</div></Card><section><div className="sectionHead"><h3>Today's Meals</h3><button className="link" onClick={()=>go('history')}>+ Log Meal</button></div><Card className="mealCard">{meals.map(([cat,name,k,logged,emoji])=><div className="meal" key={cat}><span className="mealIcon">{emoji}</span><div><b>{cat}</b><p>{name}{logged&&<> · {k} kcal</>}</p></div>{logged?<span className="done">✓</span>:<button className="add" onClick={()=>go('food_analysis')}>＋</button>}</div>)}</Card></section><Card className="coach"><div className="coachTitle"><span className="aiIcon">✦</span><b>AI Coach</b><button className="link" onClick={()=>go('ai_coach')}>View Coach</button></div><p>You're doing well on protein today. A protein-rich dinner could help you stay on target.</p></Card></div></Shell>}
function Metric({icon,label,value,pct}){return <div className="metric"><span>{icon}</span><small>{label}</small><b>{value}</b><div className="miniBar"><i style={{width:pct+'%'}}/></div></div>}
function Macro({label,value,pct,coral}){return <div className="macro"><div><b>{label}</b><span>{value}</span></div><div className="macroBar"><i className={coral?'coral':''} style={{width:pct+'%'}}/></div></div>}
function History(){return <Shell active="history"><div className="page"><Top title="History" back={false}/><p className="sub">Your meals and nutrition activity</p><Card><div className="search"><Search size={18}/><input placeholder="Search meals..."/></div><div className="historyList">{meals.slice(0,3).map(([cat,name,k,logged,emoji])=><div className="historyItem" key={cat}><span className="mealIcon">{emoji}</span><div><b>{name}</b><p>Today · {logged?k+' kcal':'Not logged'}</p></div><ChevronRight/></div>)}</div></Card><Card><h3>Daily Nutrition History</h3><p>Review your daily calorie and macro history.</p><Button small onClick={()=>go('daily_analysis_history')}>View Daily History</Button></Card><Card><h3>Food Analysis History</h3><p>Previously analyzed meals and AI insights.</p><Button small onClick={()=>go('food_analysis_history')}>View Food History</Button></Card></div></Shell>}
function Progress(){return <Shell active="progress"><div className="page"><Top title="Progress" back={false}/><p className="sub">Your health journey at a glance</p><div className="progressHero"><small>GOAL PROGRESS</small><h1>45%</h1><p>13.7 lb lost · 16.4 lb remaining</p><div className="ring"><span>45%</span></div></div><div className="stats four"><Stat n="85" l="Average Score"/><Stat n="+12%" l="Total Improvement"/><Stat n="18" l="Consistency Days"/><Stat n="45%" l="Goal Progress"/></div><Card><div className="sectionHead"><div><small>WEEKLY TREND</small><h3>Nutrition Score Over Time</h3></div><button className="link">View All</button></div><div className="chart"><div className="line"/>{[62,70,68,76,81,78,85].map((n,i)=><i key={i} style={{left:(i*16.5)+'%',bottom:n+'%'}} title={n}/>)}</div></Card><Card><div className="sectionHead"><div><small>BODY METRICS</small><h3>Your health snapshot</h3></div><button className="link">Details</button></div>{[['Weight','181.4 / 165 lb','45%'],['Calories','1420 / 1800 kcal','79%'],['Protein','92 / 120 g','77%']].map(x=><div className="goalRow" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></div>)}</Card><Card className="quote">“A steady path, one healthy choice at a time.”</Card></div></Shell>}
function Stat({n,l}){return <div className="stat"><b>{n}</b><small>{l}</small></div>}
function AICoach(){const [msgs,setMsgs]=useState([{from:'ai',text:"I'm your AI Nutrition Coach.\nHow can I help you today?"}]);const [v,setV]=useState('');const send=()=>{if(!v.trim())return;const x=v;setV('');setMsgs(m=>[...m,{from:'user',text:x},{from:'ai',text:'That is a great question. Based on your current weight-loss goals, keep protein consistent and choose a balanced meal.'}])};return <Shell active="ai_coach"><div className="page"><Top title="AI Coach" back={false}/><p className="sub">Your personal nutrition expert</p><Card className="chat"><div className="chatTop"><b>Chat with AI Coach</b><button className="link" onClick={()=>setMsgs([])}>Clear Chat</button></div><div className="messages">{msgs.map((m,i)=><div key={i} className={'msg '+m.from}>{m.text}</div>)}</div><div className="chips">{['Nutrition Advice','Meal Ideas','Health Insights','Ask Anything'].map(x=><button key={x} onClick={()=>setV(x)}>{x}</button>)}</div><div className="composer"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Type your message..."/><button onClick={send}><Send size={18}/></button></div></Card><Card><h3>Coach Insights</h3><p>You're doing well on protein today. A protein-rich dinner could help you stay on target.</p></Card></div></Shell>}
function Profile(){const items=[['Personal Details','Update your name, age, height, weight','personal_details',User],['Health Goal','Weight Loss','goal',Target],['Dietary Preferences','Manage food preferences','goal',Utensils],['Notifications','Manage reminders and alerts','permission',Bell],['Privacy & Security','Manage your data and privacy','legal_privacy',Shield],['Help Center','FAQs, guides and support','help_support',HelpCircle],['About','App version 1.0','about_app',Info],['Premium','Unlock premium features','premium',Sparkles]];return <Shell active="profile"><div className="page"><Top title="Profile" back={false}/><Card className="profileHero"><div className="bigAvatar"><User/></div><h2>Gogo Ji</h2><p>Member since 2026</p><div className="stats three"><Stat n="7" l="Current streak"/><Stat n="85" l="Avg. nutrition score"/><Stat n="18" l="Days tracked"/></div></Card><Card className="menuCard">{items.map(([t,s,r,C])=><button className="menuItem" key={t} onClick={()=>go(r)}><span className="menuIcon"><Icon C={C}/></span><span><b>{t}</b><small>{s}</small></span><ChevronRight size={18}/></button>)}</Card><Button outline onClick={()=>go('login')}>Log Out</Button></div></Shell>}
function Goal(){return <Shell><div className="page"><Top title="Switch Nutrition Goal"/><p className="sub">Choose the goal that best matches your current journey.</p><div className="goalCards">{[['Weight Loss','Create a sustainable calorie deficit while nourishing your body.','✓'],['Muscle Gain','Support strength and muscle growth with balanced nutrition.',''],['Heart Health','Prioritize heart-friendly foods and healthy habits.',''],['Diabetes-Friendly','Make smart choices for steadier glucose.',''],['Cancer-Aware','Support nourishing choices with awareness-focused guidance.','']].map(([t,d,s],i)=><Card key={t} className={'goalCard '+(i===0?'selected':'')} onClick={()=>go('home')}><div className="goalCheck">{i===0?'✓':''}</div><div><h3>{t}</h3><p>{d}</p></div></Card>)}</div></div></Shell>}
function FoodAnalysis(){return <Shell><div className="page"><Top title="Food Analysis"/><p className="sub">Scan, search, or speak to log your meal</p><Card className="scan"><div className="camera"><Camera size={42}/><b>Tap to scan your food</b><small>Align your meal within the frame</small></div><Button onClick={()=>go('food_analysis_result')}>Scan Food</Button></Card><div className="or"><span/> OR <span/></div><div className="choiceGrid"><Card onClick={()=>go('food_analysis_result')}><Search/><h3>Search Food</h3><p>Find a meal from our food database</p></Card><Card><Mic/><h3>Voice Input</h3><p>Tell us what you ate</p></Card><Card><Image/><h3>Gallery / Add Photo</h3><p>Choose a photo from your gallery</p></Card></div></div></Shell>}
function FoodResult(){return <Shell><div className="page"><Top title="Food Analysis Result" right={<button className="iconBtn"><span>↗</span></button>}/><Card className="foodSummary"><div className="foodEmoji">🍗</div><div><h2>Grilled Chicken Bowl</h2><p>Chicken, grains, greens & vegetables</p><span className="score">85/100</span></div></Card><Card><div className="sectionHead"><h3>Nutrition</h3><span>Great choice</span></div><div className="nutritionGrid"><Stat n="520" l="Calories"/><Stat n="42g" l="Protein"/><Stat n="48g" l="Carbs"/><Stat n="16g" l="Fat"/></div></Card><Card><h3>AI Insight</h3><p>Great choice! High in protein and fiber. Consider adding more leafy greens tomorrow.</p></Card><Button onClick={()=>go('history')}>Save to History</Button></div></Shell>}
function Simple({title,children}){return <Shell><div className="page"><Top title={title}/><Card className="simple">{children||<><h3>{title}</h3><p>This section is available in the VitaAI app. The web version preserves the same navigation and visual system.</p></>}</Card></div></Shell>}
function App(){const p=path();switch(p){case'splash':return <Splash/>;case'login':return <Login/>;case'register':return <Register/>;case'forgot_password':return <Forgot/>;case'home':return <Home/>;case'history':return <History/>;case'progress':return <Progress/>;case'ai_coach':return <AICoach/>;case'profile':return <Profile/>;case'goal':return <Goal/>;case'food_analysis':return <FoodAnalysis/>;case'food_analysis_result':return <FoodResult/>;case'personal_details':return <Simple title="Personal Details"><label>Name<input defaultValue="Gogo Ji"/></label><label>Age<input defaultValue="29"/></label><label>Height<input defaultValue={'5\'9"'}/></label><label>Current weight<input defaultValue="181.4 lb"/></label><Button onClick={()=>go('profile')}>Save</Button></Simple>;case'premium':return <Simple title="VitaAI Premium"><h2>VitaAI Premium</h2><p>Unlock premium nutrition insights, advanced coaching and enhanced tracking.</p><Button onClick={()=>go('profile')}>Continue</Button></Simple>;default:return <Simple title={p.replaceAll('_',' ')}/>}}
createRoot(document.getElementById('root')).render(<App/>);